{% set name = "cloud-sql-proxy" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GoogleCloudPlatform/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ab7645db293eb88538fa9196f3d2cd5c1c0743d9bde091aa5180e237e8615285

build:
  number: 0
  script:
    - cd cmd/cloud_sql_proxy && go-licenses save . --save_path ../../library_licenses
    - go build -v -o $PREFIX/bin/cloud_sql_proxy  # [not win]
    - go install -v .          # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - cloud_sql_proxy --help

about:
  home: https://github.com/GoogleCloudPlatform/cloud-sql-proxy
  license: Apache-2.0
  license_file:
    - library_licenses/
    - LICENSE
  summary: A utility for connecting securely to your Cloud SQL instances

extra:
  recipe-maintainers:
    - xhochy
