schema_version: 1

context:
  name: cloud-sql-proxy
  version: "2.17.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/GoogleCloudPlatform/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 8c48d9724e2084cabf7f001fe2cbd9dce33143dd720e55797fa4b15fe6921e66

build:
  number: 0
  script:
    - if: not win
      then: mkdir $PREFIX/bin && go build && cp cloud-sql-proxy $PREFIX/bin
      else: go install -v .
    - cd cmd && go-licenses save . --save_path ../library_licenses

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - cloud-sql-proxy --help

about:
  license: Apache-2.0
  license_file:
    - library_licenses/
    - LICENSE
  summary: A utility for connecting securely to your Cloud SQL instances
  homepage: https://github.com/GoogleCloudPlatform/cloud-sql-proxy

extra:
  recipe-maintainers:
    - xhochy
